#!/usr/bin/env python3
"""Generate static JSON files for the S3 static site.

Produces the same JSON that the live server returns for:
  GET /api/parts  ->  web/static/api/parts.json
  GET /params/all ->  web/static/params/all.json

Run from project root: python3 scripts/generate_static.py
"""
import json
import os
import sys
from collections import OrderedDict
from hashlib import sha256

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from danger.finger import DangerFinger, PART_COLORS
from danger.finger_params import DangerFingerParams as P, FingerPart

STATIC_DIR = os.path.join(PROJECT_ROOT, "web", "static")

PARTS = [
    FingerPart.TIP, FingerPart.BASE, FingerPart.LINKAGE, FingerPart.MIDDLE,
    FingerPart.TIPCOVER, FingerPart.SOCKET, FingerPart.PLUG, FingerPart.BUMPER,
    FingerPart.STAND,
]


def _preview_config():
    """Replicate the preview config logic from web/server.py without importing it."""
    return {
        "rotateOffsets": {k: list(v) for k, v in P._preview_rotate_offsets.items()},
        "positionOffsets": {k: list(v) for k, v in P._preview_position_offsets.items()},
        "plugInstances": [
            {"position": list(p["position"]), "rotation": list(p["rotation"])}
            for p in P._preview_plug_instances
        ],
        "explodeOffsets": {k: list(v) for k, v in P._preview_explode_offsets.items()},
        "partColors": {k: v for k, v in PART_COLORS.items()},
        "hingePivots": {k: list(v) for k, v in P._preview_hinge_pivots.items()},
    }


def generate_parts_json():
    part_list = [{"id": str(p.name).lower(), "label": str(p.name).capitalize()} for p in PARTS]
    data = {
        "parts": part_list,
        "version": DangerFinger.VERSION,
        "build": "static",
        "previewConfig": _preview_config(),
        "defaultCfghash": _default_cfghash(),
        "wpAuthUrl": os.environ.get("WP_AUTH_URL", "https://dangercreations.com"),
        "appBaseUrl": os.environ.get("APP_BASE_URL", ""),
        "staticSiteUrl": os.environ.get("STATIC_SITE_URL", ""),
    }
    out = os.path.join(STATIC_DIR, "api", "parts.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(data, f, default=str, separators=(",", ":"))
    print(f"  Wrote {out} ({os.path.getsize(out)} bytes)")


def generate_params_json():
    params = DangerFinger().get_params(adv=False, allv=True, extended=True)
    out = os.path.join(STATIC_DIR, "params", "all.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(params, f, default=str, skipkeys=True, separators=(",", ":"))
    print(f"  Wrote {out} ({os.path.getsize(out)} bytes)")


def _default_cfghash():
    """Compute the cfghash for the default (empty) config, matching server.py's package_config_json."""
    config = OrderedDict(sorted({}.items(), key=lambda t: t[0]))
    return sha256(json.dumps(config, skipkeys=True).encode("utf-8")).hexdigest()


def generate_bootstrap_js():
    """Write a JS file that embeds parts + params data as globals.

    CloudFront routes /api/* and /params/* to EC2, so the static JSON files in
    S3 are never reached. This bootstrap file is loaded before api.js and
    provides the data directly, eliminating the need for XHR on first load.
    """
    parts_data = {
        "parts": [{"id": str(p.name).lower(), "label": str(p.name).capitalize()} for p in PARTS],
        "version": DangerFinger.VERSION,
        "build": "static",
        "previewConfig": _preview_config(),
        "defaultCfghash": _default_cfghash(),
        "wpAuthUrl": os.environ.get("WP_AUTH_URL", "https://dangercreations.com"),
        "appBaseUrl": os.environ.get("APP_BASE_URL", ""),
        "staticSiteUrl": os.environ.get("STATIC_SITE_URL", ""),
    }
    params_data = DangerFinger().get_params(adv=False, allv=True, extended=True)

    parts_json = json.dumps(parts_data, default=str, separators=(",", ":"))
    params_json = json.dumps(params_data, default=str, skipkeys=True, separators=(",", ":"))

    js = (
        "// Auto-generated by generate_static.py — do not edit.\n"
        "window.__STATIC_PARTS__=" + parts_json + ";\n"
        "window.__STATIC_PARAMS__=" + params_json + ";\n"
    )
    out = os.path.join(STATIC_DIR, "config-bootstrap.js")
    with open(out, "w") as f:
        f.write(js)
    print(f"  Wrote {out} ({os.path.getsize(out)} bytes)")


def main():
    print("Generating static JSON files...")
    generate_parts_json()
    generate_params_json()
    generate_bootstrap_js()
    print("Done.")


if __name__ == "__main__":
    main()
